version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-south-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-south-1}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    command: celery -A worker.app worker --loglevel=info --concurrency=4
