services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    env_file:
      - .env
